### ISSUE TITLE
Keeps running same script

### ISSUE THREAD

**Issue by fredrikekre** [andrcar/RunMatlabRemotely#2]
I think it should remember what scripts that has already been run in a tmp file and not run them again.

**Comment by andrcar** [comment]
This is a good idea. However, this script was initially developed to run time consuming stochastic optimisation. These scripts are not expected to yield the same result over and over so many evaluations are favourable. The ability to choose the number of runs for specific scripts wil be implemented in the future. Thank you for your feedback.
